# Generated by Django 5.0.1 on 2024-01-31 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='business',
            unique_together={('latitude', 'longitude')},
        ),
    ]
