# Generated by Django 5.0.1 on 2024-01-31 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0002_alter_business_unique_together'),
    ]

    operations = [
        migrations.RenameField(
            model_name='business',
            old_name='geohash',
            new_name='geo_hash',
        ),
        migrations.RemoveField(
            model_name='business',
            name='max_latitude',
        ),
        migrations.RemoveField(
            model_name='business',
            name='max_longitude',
        ),
        migrations.RemoveField(
            model_name='business',
            name='min_latitude',
        ),
        migrations.RemoveField(
            model_name='business',
            name='min_longitude',
        ),
    ]
